import React from 'react';
import {
  Activity,
  Badge,
  BarChart3,
  Braces,
  Bug,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CirclePlus,
  CircleStop,
  ClipboardCheck,
  CloudCheck,
  CloudUpload,
  Code,
  Cross,
  Droplets,
  FileText,
  Flag,
  FlaskConical,
  GitBranch,
  HeartPulse,
  History,
  Info,
  ListChecks,
  LoaderCircle,
  Lock,
  LogIn,
  Mars,
  MessageSquare,
  Mic,
  Pause,
  Pill,
  Play,
  RefreshCw,
  Settings,
  ShieldCheck,
  Sparkles,
  SquarePen,
  Stethoscope,
  ThumbsUp,
  Timer,
  TrendingUp,
  TriangleAlert,
  X,
  ArrowLeft,
} from 'lucide-react';

const iconMap = {
  account_tree: GitBranch,
  add_circle: CirclePlus,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  auto_awesome: Sparkles,
  badge: Badge,
  bloodtype: Droplets,
  calendar_month: Calendar,
  calendar_today: Calendar,
  chat_bubble: MessageSquare,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_done: CloudCheck,
  cloud_sync: CloudUpload,
  code: Code,
  coronavirus: Bug,
  data_object: Braces,
  description: FileText,
  edit: SquarePen,
  error: CircleAlert,
  event: CalendarCheck,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  flag: Flag,
  glucose: Activity,
  history: History,
  info: Info,
  list_alt: ListChecks,
  local_hospital: Cross,
  lock: Lock,
  login: LogIn,
  male: Mars,
  medication: Pill,
  mic: Mic,
  monitor_heart: HeartPulse,
  pause: Pause,
  pill: Pill,
  play_arrow: Play,
  prescriptions: Pill,
  progress_activity: LoaderCircle,
  pulmonology: Activity,
  schedule: Timer,
  science: FlaskConical,
  security: ShieldCheck,
  settings: Settings,
  stethoscope: Stethoscope,
  stop_circle: CircleStop,
  sync: RefreshCw,
  thumb_up: ThumbsUp,
  timer: Timer,
  trending_up: TrendingUp,
  verified_user: ShieldCheck,
  warning: TriangleAlert,
};

function Icon({ name, filled = false, className = '' }) {
  const SvgIcon = iconMap[name] || Circle;
  return <SvgIcon aria-hidden="true" className={`icon ${filled ? 'filled' : ''} ${className}`} />;
}

export default Icon;
