[project]
name = "medical-documentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aman Prakash", email = "amankumar.prakash@nitorinfotech.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
medical-documentation = "medical_documentation:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
