/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StartEncounterRouteImport } from './routes/start-encounter'
import { Route as SyncRouteImport } from './routes/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StartEncounterRoute = StartEncounterRouteImport.update({
  id: '/start-encounter',
  path: '/start-encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/record': typeof RecordRoute
  '/review': typeof ReviewRoute
  '/start-encounter': typeof StartEncounterRoute
  '/sync': typeof SyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/record': typeof RecordRoute
  '/review': typeof ReviewRoute
  '/start-encounter': typeof StartEncounterRoute
  '/sync': typeof SyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/record': typeof RecordRoute
  '/review': typeof ReviewRoute
  '/start-encounter': typeof StartEncounterRoute
  '/sync': typeof SyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analysis' | '/record' | '/review' | '/start-encounter' | '/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis' | '/record' | '/review' | '/start-encounter' | '/sync'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/record'
    | '/review'
    | '/start-encounter'
    | '/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  RecordRoute: typeof RecordRoute
  ReviewRoute: typeof ReviewRoute
  StartEncounterRoute: typeof StartEncounterRoute
  SyncRoute: typeof SyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-encounter': {
      id: '/start-encounter'
      path: '/start-encounter'
      fullPath: '/start-encounter'
      preLoaderRoute: typeof StartEncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  RecordRoute: RecordRoute,
  ReviewRoute: ReviewRoute,
  StartEncounterRoute: StartEncounterRoute,
  SyncRoute: SyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
